language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer install --prefer-dist
  - chmod +x app/yiic
  - app/yiic permissions
  - app/yiic environment change dev

script: vendor/bin/codecept run

branches:
  only:
    - master